package com.gitee.taven.entity.business;

public class UserInformations {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_informations.id
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_informations.userid
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_informations.email
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_informations.address
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_informations.id
     *
     * @return the value of user_informations.id
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_informations.id
     *
     * @param id the value for user_informations.id
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_informations.userid
     *
     * @return the value of user_informations.userid
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_informations.userid
     *
     * @param userid the value for user_informations.userid
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_informations.email
     *
     * @return the value of user_informations.email
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_informations.email
     *
     * @param email the value for user_informations.email
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_informations.address
     *
     * @return the value of user_informations.address
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_informations.address
     *
     * @param address the value for user_informations.address
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}