# pg
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/test
#    username: postgres
#    password: pgpwd


# mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/testj
    username: root
    password: root
    hikari:
      maximum-pool-size: 3000

# mysql
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
#    hikari:
#      maximum-pool-size: 1000