package com.gitee.taven.mapper.business;

import com.gitee.taven.entity.business.UserInformations;
import com.gitee.taven.entity.business.UserInformationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInformationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    long countByExample(UserInformationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    int deleteByExample(UserInformationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    int insert(UserInformations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    int insertSelective(UserInformations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    List<UserInformations> selectByExample(UserInformationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    UserInformations selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserInformations record, @Param("example") UserInformationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    int updateByExample(@Param("record") UserInformations record, @Param("example") UserInformationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    int updateByPrimaryKeySelective(UserInformations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_informations
     *
     * @mbg.generated Tue Oct 16 11:40:15 CST 2018
     */
    int updateByPrimaryKey(UserInformations record);
}